<?php

namespace AppBundle\Repository;

/**
 * HouseKeepingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseKeepingRepository extends \Doctrine\ORM\EntityRepository
{
}
