<?php

namespace AppBundle\Repository;

/**
 * ReceptionistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionistRepository extends \Doctrine\ORM\EntityRepository
{
}
